@startuml
set separator none
title Project Service

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

Container_Boundary("FwsApplication.FwsApplication_boundary", "FwsApplication", $tags="") {
  Component(FwsApplication.FwsApplication.Core, "Core", $techn="Module", $descr="", $tags="", $link="")
  Component(FwsApplication.FwsApplication.ProjectService, "Project Service", $techn="Module", $descr="", $tags="", $link="")
  Component(FwsApplication.FwsApplication.Support, "Support", $techn="Module", $descr="", $tags="", $link="")
}

Rel(FwsApplication.FwsApplication.ProjectService, FwsApplication.FwsApplication.Core, "depends on", $techn="", $tags="", $link="")
Rel(FwsApplication.FwsApplication.ProjectService, FwsApplication.FwsApplication.Support, "uses", $techn="", $tags="", $link="")
Rel(FwsApplication.FwsApplication.Support, FwsApplication.FwsApplication.Core, "depends on", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml