@startuml
set separator none
title Core

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

Container_Boundary("FwsApplication.FwsApplication_boundary", "FwsApplication", $tags="") {
  Component(FwsApplication.FwsApplication.Core, "Core", $techn="Module", $descr="", $tags="", $link="")
}


SHOW_LEGEND(true)
@enduml